stages:
    - npm
    - test

npm:
    stage: npm
    tags:
        - type-inference
    script:
        - npm ci
        - npm run build
    cache:
        paths:
            - node_modules/
            - built/

test:
    stage: test
    tags:
        - type-inference
    dependencies:
        - npm
    script:
        - ls node_modules/
        - npm test