stages:
    - npm
    - test

cache:
    key: modules
    paths:
        - node_modules/
        - built/
        - src/parsing/

npm:
    stage: npm
    tags:
        - type-inference
    script:
        - npm ci
        - npm run build
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/

test:
    stage: test
    tags:
        - type-inference
    dependencies:
        - npm
    script:
        - ls node_modules/
        - npm test
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/
        policy: pull