image: node:latest

stages:
    - build
    - lint

build:
    stage: build
    tags:
        - type-inference
    script:
        - npm ci

lint:
    stage: lint
    needs:
        - build
    tags:
        - type-inference
    script:
        - npm run lint