stages:
    - setup
    - lint
    - tests

cache:
    key: modules
    paths:
        - node_modules/
        - built/
        - src/parsing/
        - test/assets/QT3TS
        - test/assets/XQUTS

setup:
    stage: setup
    tags:
        - type-inference
    script:
        - npm ci
        - npm run build
        - mkdir -p ./test/assets/XQUTS ./test/assets/QT3TS
        - curl -L https://github.com/LeoWoerteler/QT3TS/archive/master.tar.gz > temp.tar.gz
        - tar -xf temp.tar.gz -C ./test/assets/QT3TS/ --strip-components=1
        - curl -L https://github.com/LeoWoerteler/XQUTS/archive/master.tar.gz > temp.tar.gz
        - tar -xf temp.tar.gz -C ./test/assets/XQUTS/ --strip-components=1
        - rm -f temp.tar.gz
        - unzip -q test/assets/QT3TS/xqueryx.zip -d ./test/assets/QT3TS/
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/
            - test/assets/QT3TS
            - test/assets/XQUTS

lint:
    stage: lint
    needs:
        - setup
    tags:
        - type-inference
    script:
        - npm run lint
    cache:
        key: modules
        paths:
            - node_modules/
        policy: pull

test:
    stage: tests
    needs:
        - setup
    tags:
        - type-inference
    script:
        - ls node_modules/
        - npm test
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/
        policy: pull
