stages:
    - npm
    - test

npm:
    stage: npm
    tags:
        - type-inference
    script:
        - npm ci
    cache:
        paths:
            - node_modules/
            - built/
    artifacts:
        expire_in: 1 days
        when: on_success
        paths:
            - node_modules/

test:
    stage: test
    tags:
        - type-inference
    dependencies:
        - npm
    script:
        - npm test