cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/
        - .npm/

stages:
    - build
    - lint

build:
    stage: build
    tags:
        - type-inference
    script:
        - npm ci --cache .npm --prefer-offline

lint:
    stage: lint
    needs:
        - build
    tags:
        - type-inference
    script:
        - ls node_modules/
        - npm --cache .npm run lint