stages:
    - setup
    - lint
    - tests

cache:
    key: modules
    paths:
        - node_modules/
        - built/
        - src/parsing/
        - test/assets/QT3TS
        - test/assets/XQUTS

setup:
    stage: setup
    tags:
        - type-inference
    script:
        - npm ci
        - npm run build
        - mkdir -p ./test/assets/XQUTS ./test/assets/QT3TS
        - curl -L https://github.com/LeoWoerteler/QT3TS/archive/master.tar.gz > temp.tar.gz
        - tar -xf temp.tar.gz -C ./test/assets/QT3TS/ --strip-components=1
        - curl -L https://github.com/LeoWoerteler/XQUTS/archive/master.tar.gz > temp.tar.gz
        - tar -xf temp.tar.gz -C ./test/assets/XQUTS/ --strip-components=1
        - rm -f temp.tar.gz
        - unzip -q test/assets/QT3TS/xqueryx.zip -d ./test/assets/QT3TS/
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/
            - test/assets/QT3TS
            - test/assets/XQUTS

lint:
    stage: lint
    needs:
        - setup
    tags:
        - type-inference
    script:
        - npm run lint
    cache:
        key: modules
        paths:
            - node_modules/
        policy: pull

ci-test:
    stage: tests
    needs:
        - setup
    tags:
        - type-inference
    script:
        - npm run ci-test
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/
        policy: pull

ci-qt3tests:
    stage: tests
    needs:
        - setup
    tags:
        - type-inference
    script:
        - npm run ci-qt3tests
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/
        policy: pull

integrationtests:
    stage: tests
    needs:
        - setup
    tags:
        - type-inference
    script:
        - npm run integrationtests
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/
        policy: pull

qt3tests:
    stage: tests
    needs:
        - setup
    tags:
        - type-inference
    script:
        - npm run qt3tests
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/
        policy: pull

ci-qt3testsxqueryx:
    stage: tests
    needs:
        - setup
    tags:
        - type-inference
    script:
        - npm run ci-qt3testsxqueryx
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/
        policy: pull

ci-xqutstests:
    stage: tests
    needs:
        - setup
    tags:
        - type-inference
    script:
        - npm run ci-xqutstests
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/
        policy: pull

ci-xqutstestsxqueryx:
    stage: tests
    needs:
        - setup
    tags:
        - type-inference
    script:
        - npm run ci-xqutstestsxqueryx
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/
        policy: pull
