stages:
    - setup
    - lint
    - tests

cache:
    key: modules
    paths:
        - node_modules/
        - built/
        - src/parsing/
        - test/assets/QT3TS
        - test/assets/XQUTS

setup-npm:
    stage: setup
    tags:
        - type-inference
    script:
        - npm ci
        - npm run build
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/

setup-qt3:
    stage: setup
    tags:
        - type-inference
    script:
        - mkdir -p ./test/assets/XQUTS ./test/assets/QT3TS
        - curl -L https://github.com/LeoWoerteler/QT3TS/archive/master.tar.gz | tar -xz -C ./test/assets/QT3TS --strip-components=1
        - curl -L https://github.com/LeoWoerteler/XQUTS/archive/master.tar.gz | tar -xz -C ./test/assets/XQUTS --strip-components=1
        - unzip -q test/assets/QT3TS/xqueryx.zip -d ./test/assets/QT3TS/
    cache:
        key: modules
        paths:
            - test/assets/QT3TS
            - test/assets/XQUTS

lint:
    stage: lint
    needs:
        - setup-npm
    tags:
        - type-inference
    script:
        - npm run lint
    cache:
        key: modules
        paths:
            - node_modules/
        policy: pull

test:
    stage: tests
    needs:
        - setup-npm
    tags:
        - type-inference
    script:
        - ls node_modules/
        - npm test
    cache:
        key: modules
        paths:
            - node_modules/
            - built/
            - src/parsing/
        policy: pull