/**
 * @enum {string}
 */
const ETypeNames = {
	ITEM: 'item()',
	XSANYSIMPLETYPE: 'xs:anySimpleType',
	XSANYATOMICTYPE: 'xs:anyAtomicType',
	XSUNTYPEDATOMIC: 'xs:untypedAtomic',
	XSSTRING: 'xs:string',
	XSBOOLEAN: 'xs:boolean',
	XSDECIMAL: 'xs:decimal',
	XSFLOAT: 'xs:float',
	XSDOUBLE: 'xs:double',
	XSDURATION: 'xs:duration',
	XSDATETIME: 'xs:dateTime',
	XSTIME: 'xs:time',
	XSDATE: 'xs:date',
	XSGYEARMONTH: 'xs:gYearMonth',
	XSGYEAR: 'xs:gYear',
	XSGMONTHDAY: 'xs:gMonthDay',
	XSGDAY: 'xs:gDay',
	XSGMONTH: 'xs:gMonth',
	XSHEXBINARY: 'xs:hexBinary',
	XSBASE64BINARY: 'xs:base64Binary',
	XSANYURI: 'xs:anyURI',
	XSQNAME: 'xs:QName',
	XSNOTATION: 'xs:NOTATION',
	XSNORMALIZEDSTRING: 'xs:normalizedString',
	XSTOKEN: 'xs:token',
	XSLANGUAGE: 'xs:language',
	XSNMTOKEN: 'xs:NMTOKEN',
	XSNMTOKENS: 'xs:NMTOKENS',
	XSNAME: 'xs:Name',
	XSNCNAME: 'xs:NCName',
	XSID: 'xs:ID',
	XSIDREF: 'xs:IDREF',
	XSIDREFS: 'xs:IDREFS',
	XSENTITY: 'xs:ENTITY',
	XSENTITIES: 'xs:ENTITIES',
	XSINTEGER: 'xs:integer',
	XSNONPOSITIVEINTEGER: 'xs:nonPositiveInteger',
	XSNEGATIVEINTEGER: 'xs:negativeInteger',
	XSLONG: 'xs:long',
	XSINT: 'xs:int',
	XSSHORT: 'xs:short',
	XSBYTE: 'xs:byte',
	XSNONNEGATIVEINTEGER: 'xs:nonNegativeInteger',
	XSUNSIGNEDLONG: 'xs:unsignedLong',
	XSUNSIGNEDINT: 'xs:unsignedInt',
	XSUNSIGNEDSHORT: 'xs:unsignedShort',
	XSUNSIGNEDBYTE: 'xs:unsignedByte',
	XSPOSITIVEINTEGER: 'xs:positiveInteger',
	XSYEARMONTHDURATION: 'xs:yearMonthDuration',
	XSDAYTIMEDURATION: 'xs:dayTimeDuration',
	FUNCTION: 'function(*)',
	MAP: 'MAP(*)',
	ARRAY: 'array(*)',
	NODE: 'node()',
	ELEMENT: 'element()',
	COMMENT: 'comment()',
	ATTRIBUTE: 'attribute()',
	PROCESSINGINSTRUCTION: 'processing-instruction()',
	DOCUMENT: 'document()',
	XSNUMERIC: 'xs:numeric'
};

export default ETypeNames;
