name: Linter
on:
    - push
    - pull_request
jobs:
    test:
        name: Linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 15
            - name: Install dependencies
              run: npm ci;
            - name: Linter
              run: npm run lint;
